### ISSUE TITLE
Configure Jenkins deployment

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/literacyapp-web#12]
- Fix Git release Maven plugin

http://stackoverflow.com/a/27019951

**Comment by jogrimst** [comment]
https://axelfontaine.com/blog/final-nail.html

**Comment by jogrimst** [comment]
http://stackoverflow.com/a/23371310/354173

**Comment by jogrimst** [comment]
http://stackoverflow.com/a/21184154/354173

**Comment by jogrimst** [comment]
https://scalalala.wordpress.com/2015/05/06/maven-release-plugin-horrors-with-git/
