### ISSUE TITLE
Plan analytics dashboard

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/literacyapp-web#17]
Write down functionalities for analytics dashboard

**Comment by literacyapp** [comment]
Ahmad, could you write down what type of analytics should be displayed on the web site dashboard?

Also, feel free to draw a simple mockup if you want.

[--- Commented from Asana.com
#commenter Jo Grimstad
---[aa]

**Comment by literacyapp** [comment]
Here is a sample dashboard for inspiration: http://www.getmdl.io/templates/dashboard/index.html

[--- Commented from Asana.com
#commenter Jo Grimstad
---[aa]

**Comment by literacyapp** [comment]
Thanks,  I'll use samples from Google analytics Dashboards. e.g: https://www.google.com/analytics/gallery/#landing/start/

[--- Commented from Asana.com
#commenter Ahmad Mekdad
---[aa]

**Comment by jogrimst** [comment]
Hi, Ahmed. Do you have a sketch ready? :-)

**Comment by jogrimst** [comment]
The files can be uploaded to Google Drive:  https://drive.google.com/drive/folders/0B9cqcH15vKi4V0NqeTJLbzE3ZWc
