### ISSUE TITLE
Ask contributor to provide time available during on-boarding

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/literacyapp-web#251]

**Comment by jogrimst** [comment]
@Alin-GFR Which alternatives should we present? Is this list okay?:

- 0-15 minutes per week
- 15-60 minutes per week
- 1-3 hours per week
- More than 3 hours per week

**Comment by jogrimst** [comment]
@Alin-GFR Is it okay to present it like this?:

![screen shot 2016-09-21 at 20 10 03](https://cloud.githubusercontent.com/assets/1451036/18721086/7f29dfdc-8037-11e6-9930-72cec08b07eb.png)

![screen shot 2016-09-21 at 20 10 13](https://cloud.githubusercontent.com/assets/1451036/18721087/7f90beaa-8037-11e6-8e8c-a4764712cf5b.png)

**Comment by jogrimst** [comment]
@Alin-GFR Can you do a code review?

https://github.com/literacyapp-org/literacyapp-web/pull/253/files

**Comment by Alin-GFR** [comment]
how much time would you make your self available for contributing

**Comment by Alin-GFR** [comment]
yes, perfect
