### ISSUE TITLE
Translate frontpage to Arabic

### ISSUE THREAD

**Issue by literacyapp** [literacyapp-org/literacyapp-web#6]
See https://github.com/literacyapp-org/literacyapp-web/blob/master/src/main/webapp/WEB-INF/i18n/messages_ar.properties

**Comment by literacyapp** [comment]
The i18n files are located at literacyapp-web/src/main/webapp/WEB-INF/i18n

[--- Commented from Asana.com
#commenter Jo Grimstad
---[aa]

**Comment by literacyapp** [comment]
The project has now been moved to a new GitHub repository: https://github.com/literacyapp-org/literacyapp-web/tree/master/src/main/webapp/WEB-INF/i18n

[--- Commented from Asana.com
#commenter Jo Grimstad
---[aa]

**Comment by literacyapp** [comment]
Related to https://app.asana.com/0/63812078237080/81815270283672

[--- Commented from Asana.com
#commenter Jo Grimstad
---[aa]

**Comment by jogrimst** [comment]
Hi, Sameh. I added 8 more translations that where missing on the frontpage: https://github.com/literacyapp-org/literacyapp-web/blob/master/src/main/webapp/WEB-INF/i18n/messages_ar.properties

Could you translate those as well?
